import { Carrier, Product, Shipment } from "./types/models";

export const demoProducts: Product[] = [
  {
    sku: "TF-BOX-001",
    name: "Caja reforzada mediana",
    category: "Home",
    weightKg: 2.4,
    dimensions: { lengthCm: 40, widthCm: 30, heightCm: 25 },
    warehouse: "Zaragoza",
    stockQuantity: 18,
    minStockThreshold: 20,
    unitCostUSD: 7.5,
    isFragile: false,
    status: "Low stock",
  },
  {
    sku: "TF-TAB-014",
    name: "Tablet industrial",
    category: "Electronics",
    weightKg: 1.1,
    dimensions: { lengthCm: 28, widthCm: 18, heightCm: 4 },
    warehouse: "Los Angeles",
    stockQuantity: 32,
    minStockThreshold: 8,
    unitCostUSD: 310,
    isFragile: true,
    status: "Active",
  },
  {
    sku: "TF-BEA-220",
    name: "Set cosmetico premium",
    category: "Cosmetics",
    weightKg: 0.6,
    dimensions: { lengthCm: 20, widthCm: 14, heightCm: 8 },
    warehouse: "Zaragoza",
    stockQuantity: 72,
    minStockThreshold: 15,
    unitCostUSD: 18,
    isFragile: true,
    status: "Active",
  },
];

export const demoCarriers: Carrier[] = [
  {
    id: "car-1",
    name: "FastLane",
    operatesIn: ["Spain", "United States"],
    baseRateUSD: 12,
    ratePerKgUSD: 1.3,
    ratePerKmUSD: 0.015,
    avgDeliveryDays: 2,
    onTimeRate: 96,
    maxWeightKg: 40,
    handlesFragile: true,
    acceptsPriority: ["Standard", "Express", "Same-day"],
  },
  {
    id: "car-2",
    name: "BudgetShip",
    operatesIn: ["Spain"],
    baseRateUSD: 8,
    ratePerKgUSD: 1.1,
    ratePerKmUSD: 0.01,
    avgDeliveryDays: 4,
    onTimeRate: 89,
    maxWeightKg: 25,
    handlesFragile: false,
    acceptsPriority: ["Standard", "Express"],
  },
];

export const demoShipment: Shipment = {
  id: "shp-9001",
  sku: "TF-TAB-014",
  quantity: 3,
  origin: "Los Angeles",
  destination: {
    city: "Madrid",
    country: "Spain",
    postalCode: "28001",
    distanceKm: 6200,
  },
  priority: "Express",
  declaredValueUSD: 1200,
  carrier: null,
  status: "Pending",
  createdAt: new Date("2026-06-20T10:00:00Z"),
};
